EXPECTED_COLUMNS = [
    "start",
    "end",
    "Hello! My name is ${NameOfTheInterviewer}, and I am working with/on behalf of the IOM, a United Nations agency that supports migrants and vulnerable communities. IOM works to ensure the orderly and humane management of migration for the benefit of all. It does so by providing different services to migrants with the help of implementing various programs in its portfolio. IOM's ESNFI program provides winterization assistance to vulnerable Afghan citizens to survive harsh winter.",
    "Do you consent to participate in this survey?",
    "Do you consent to share your personal data with other humanitarian agencies if request for further assessment, evaluation or assistance?",
    "A.1.Interviewer name",
    "A.2.Organization name",
    "A.1.1.Region",
    "A.1.2.Province",
    "A.1.3.District",
    "A.1.4.Village",
    "A.2.1.Type of beneficiary",
    "Other",
    "A.2.2.Which country you are returned from?",
    "Other",
    "A.2.3.Incident type",
    "Other",
    "A.2.4.Incident\\returning date",
    "A.3.2 Assistance distribution date",
    "A.3.3 Date of PDME",
    "B.1.Beneficiary/Respondent name",
    "B.2.Father name",
    "B.3.Contact #",
    "B.1.1.Respondent is head of family?",
    "B.1.2.Respondent resationship with head of family",
    "Other",
    "B.1.3.Respondent gender",
    "B.1.4.Respondent marital status",
    "B.2.1. Family size (# of Individuals)",
    "B.2.2.Number of the families in the household",
    "B.3.1.Number of Boys",
    "B.3.2.Number of Girls",
    "B.3.3.Number of Women",
    "B.3.4.Number of Men",
    "total",
    "Total male and female are:",
    "B.3.5.Is there any vulnerable member in the family?",
    "B.3.6.Type of vulnerability",
    "B.3.6.Type of vulnerability/Female headed family",
    "B.3.6.Type of vulnerability/Child headed family",
    "B.3.6.Type of vulnerability/Elderly headed family",
    "B.3.6.Type of vulnerability/Physically disabled (PD)",
    "B.3.6.Type of vulnerability/Chronically ill (CI)",
    "B.3.6.Type of vulnerability/Drug addicted (DA)",
    "B.3.6.Type of vulnerability/Mentally ill (MI)",
    "B.3.6.Type of vulnerability/Other",
    "Other",
    "D.1.Was there any assessment conducted (after incident)?",
    "If No, could you please tell us how you were selected:",
    "D.2.If Yes, Who conducted the assessment?",
    "If other, please specify:",
    "D.3.Did IOM staff visit your house to assess your needs?",
    "D.4.If No, where were you assessed?",
    "If Other, please specify:",
    "D.5.Was selection of beneficiaries done fairly?",
    "D.6.If No, reason?",
    "E.1 How you were notified about the distribution?",
    "If Other, please specify:",
    "E.2.Which kind of assistance did your family receive?",
    "E.3.Which currency did your family receive?",
    "E.4.What amount of cash did your family receive?",
    "E.5.Where did you collect the cash?",
    "If Other, please specify",
    "E.6.Was IOM staff present when you received the cash?",
    "E.7.Were you informed about the amount of cash and NFIs you would receive prior to distribution?",
    "E.8.In case No, briefly explain (in 100 characters)",
    "E.9.Did anyone from IOM office explain how the cash should be spent?",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Non-Food Items (kitchen equipment, stove, etc.)",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Foods",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Rent",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Shelter repairs or construction",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Health",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Transportation",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Heating material",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Education",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Savings",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Debt payment",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Other",
    "E.10.According to explaination by IOM staff, what items you were told to procure with the received cash?/Can't exactly recall",
    "If Other, please specify:",
    "E.11.Was there any improper procedure/behavior by the distribution staff?",
    "E.12.If Yes, What improper procedures/behavior?",
    "E.12.If Yes, What improper procedures/behavior?/Improper behavior by staff at distribution",
    "E.12.If Yes, What improper procedures/behavior?/Request for bribe",
    "E.12.If Yes, What improper procedures/behavior?/Discrimination towards women",
    "E.12.If Yes, What improper procedures/behavior?/Discrimination towards minorities",
    "E.12.If Yes, What improper procedures/behavior?/Distribution made on the basis of relationships",
    "E.13.Did you face any problem during the distribution?",
    "E.14.In case \"Yes\", what problems?",
    "E.14.In case \"Yes\", what problems?/Had to wait 2 hours or more to get the cash",
    "E.14.In case \"Yes\", what problems?/No crowd control",
    "E.14.In case \"Yes\", what problems?/Access to phone/SIM",
    "E.14.In case \"Yes\", what problems?/Long travel time/distance",
    "E.14.In case \"Yes\", what problems?/Staff misbehavior",
    "E.14.In case \"Yes\", what problems?/No child care/dependent",
    "E.14.In case \"Yes\", what problems?/Female needed male to accompany",
    "E.14.In case \"Yes\", what problems?/Distribution duration too long",
    "E.14.In case \"Yes\", what problems?/Did not feel safe in the distribution location",
    "E.14.In case \"Yes\", what problems?/Did not feel comfortable because men and women were not separated",
    "E.14.In case \"Yes\", what problems?/People at the distribution were not cooperative",
    "E.14.In case \"Yes\", what problems?/Other",
    "If Other, please explain:",
    "E.15. Was the distribution venue accomodated with the required facilities?",
    "E.15. Was the distribution venue accomodated with the required facilities?/Waiting area for male and female",
    "E.15. Was the distribution venue accomodated with the required facilities?/Latrines for male and female",
    "E.15. Was the distribution venue accomodated with the required facilities?/Drinking water",
    "E.15. Was the distribution venue accomodated with the required facilities?/Chairs/Carpet",
    "E.15. Was the distribution venue accomodated with the required facilities?/Other",
    "If Other, please specify:",
    "F.1.How long did you travel to collect the assistance by public transport (one-way)?",
    "F.2.Did you pay for transportation to and from the distribution point?",
    "If Yes, how much?",
    "F.3.Did you receive any amount for transportation cost you incured?",
    "If Yes, how much?",
    "F.4.Did you face any security concerns when traveling to/from the distribution point?",
    "If Yes, please explain what specific security concern you face:",
    "F.5.How long did it take you the last time you went to the nearby market by public transport(one-way)?",
    "G.1.Did you receive NFIs?",
    "G.2.Items distributed by IOM",
    "G.2.Items distributed by IOM/Blanket Module",
    "G.2.Items distributed by IOM/Winter Clothing Module",
    "G.2.Items distributed by IOM/Family Module",
    "G.2.Items distributed by IOM/Solar Module",
    "G.2.Items distributed by IOM/Emergency Shelter Module",
    "G.2.Items distributed by IOM/Family Tent Module",
    "G.2.10.Blanket Module (QTY)",
    "G.2.11.Blanket Module (Quality of received NFIs)",
    "G.2.12. Blanket Module (Utilization of NFIs)",
    "If \"Not used\", \"Donated\" or sold, please explain the reason:",
    "G.2.13.Winter Clothing Module (QTY)",
    "G.2.14.Winter Clothing Module (Quality of received NFIs)",
    "G.2.15.Winter Clothing Module (Utilization of NFIs)",
    "If \"Not used\", \"Donated\" or sold, please explain the reason:",
    "Family Module (QTY)",
    "Family Module (Quality of received NFIs)",
    "Family Module (Utilization of NFIs):",
    "If \"Not used\", \"Donated\" or sold, please explain the reason:",
    "G.3.What additional items do you suggest to be included in the composition of the NFI/Kit?",
    "Suggestion 2",
    "Suggestion 3",
    "H.1.Was the assistance delivered on time?",
    "If No, why?",
    "H.2.Did the assistance have any impact on your family's relationship with the rest of community?",
    "If it created tension, please explain how and why:",
    "If it reduced tensions/improved relations with the community, please explain how and why:",
    "If other, please specify:",
    "H.3.Which distributed kits (Modules) did you find the most useful?",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Blanket Module",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Winter Clothing Module",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Family Moduel",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Solar Module",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Emergency Shelter Module",
    "H.3.Which distributed kits (Modules) did you find the most useful?/Family Tent Module",
    "H.4. Are there any kits that you did not use?",
    "H.5.Which distributed kits (Modules) you did not use?",
    "H.5.Which distributed kits (Modules) you did not use?/Blanket Module",
    "H.5.Which distributed kits (Modules) you did not use?/Winter Clothing Module",
    "H.5.Which distributed kits (Modules) you did not use?/Family Module",
    "H.5.Which distributed kits (Modules) you did not use?/Solar Module",
    "H.5.Which distributed kits (Modules) you did not use?/Emergency Shelter Module",
    "H.5.Which distributed kits (Modules) you did not use?/Family Tent Module",
    "Can you please tell us why you did not use?",
    "H.6.Did the kits meet the urgent needs of the HH?",
    "If \"No\" or \"partially\", please explain:",
    "I.1.Did you pay to anyone to receive assistance?",
    "I.2.If Yes, whom did you pay to?",
    "If Other, please specify:",
    "I.3.What did you pay?",
    "I.3.What did you pay?/Cash",
    "I.3.What did you pay?/In-Kind",
    "If Cash, How much?",
    "If In-Kind, what kind of In-kind?",
    "I.4.What modality of assistance do you prefer?",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Community elder/leader (IDP representative malek, shura leader, etc.)",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Organization staff face-to-face",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Call the organization by phone",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Goverment staff",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Call AWAZ service",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Afraid-will not get assistance in future if complain",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Nothing",
    "I.6.What would you do if you had questions or a problem with the cash or in-kind assistance?/Other",
    "If Other, Please specify:",
    "J.1.Are you satisfied with the assistance provided by IOM?",
    "If No, please explain the reason:",
    "J.2.Was the assistance appropriately met your urgent needs?",
    "J.3. Please explain the reason:",
    "K.1.How did you spend the cash received from IOM?",
    "K.1.How did you spend the cash received from IOM?/Non-Food Items (kitchen equipment, stove, etc.)",
    "K.1.How did you spend the cash received from IOM?/Foods",
    "K.1.How did you spend the cash received from IOM?/Rent",
    "K.1.How did you spend the cash received from IOM?/Shelter repairs or construction",
    "K.1.How did you spend the cash received from IOM?/Health",
    "K.1.How did you spend the cash received from IOM?/Transportation",
    "K.1.How did you spend the cash received from IOM?/Heating material",
    "K.1.How did you spend the cash received from IOM?/Education",
    "K.1.How did you spend the cash received from IOM?/Savings",
    "K.1.How did you spend the cash received from IOM?/Debt payment",
    "K.1.How did you spend the cash received from IOM?/Other",
    "If Other, please explain:",
    "K.2.Did you do any of the following during last/this winter to survive the cold times?",
    "K.2.Did you do any of the following during last/this winter to survive the cold times?/Send children to collect firewood",
    "K.2.Did you do any of the following during last/this winter to survive the cold times?/Decrease daily food ration to save money for fuel",
    "K.2.Did you do any of the following during last/this winter to survive the cold times?/Sleep in overcrowded room",
    "K.2.Did you do any of the following during last/this winter to survive the cold times?/Borrow cash to buy fuel",
    "K.3.If cash is borrowed, indicate the amount (AFN)",
    "K.4.What type of fuel does your family mostly use?",
    "If Other, please explain:",
    "K.5.How many blankets did you have last winter?",
    "K.6.Did you have heating device last winter?",
    "K.7.Did you have enough fuel last winter?",
    "L.1.Are you aware of of IOM Feedback and Complaint Mechanism (CFM)?",
    "L.2.If Yes, have you ever registered any feedback/complaint?",
    "If not, What would prevent you from submitting a complaint or giving feedback?",
    "If other, please explain:",
    "L.3. If yes, did you receive any response to the complaint or feedback?",
    "L.4. If yes, how satisfied are you with the response you received?",
    "Please explain the reason:",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/AWAAZ-410",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Community Shura",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Local authorities (ANDMA and/or DoRR)",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Hotline No/SMS",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/IOM Staff",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Email",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Other",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Community leader",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Don't Know",
    "L.3.What approach do you perefer to submit a complaint/feedback(If any) ?/Prefer not to answer",
    "If Other, please specify:",
    "Beneficiary face image",
    "Beneficiary face image_URL",
    "Interveiwee Additional Comments/Remarks",
    "A.3.1 RAF assessment date",
    "C.1.What is your HH average income (AFN) per month?",
    "Other",
    "I.3.How much did you pay?",
    "_id",
    "_uuid",
    "_submission_time",
    "_validation_status",
    "_notes",
    "_status",
    "_submitted_by",
    "__version__",
    "_tags",
    "meta/rootUuid",
    "_index"
]