# -*- coding: utf-8 -*-

APPROVED_INTERVIEWERS = [
    "Fahimullah Rasa",
    "Sadiqullah Afkar",
    "Rihanullah Mashwani",
    "Qayamudin Amiri",
    "Hina Rasa",
    "Samiullah sahir",
    "Qaseem kamawal",
    "Zarmina Sadat",
    "Ahmad Javid Karimi",
    "Nasrullah Mohmand",
    "Mohammad Akbar",
    "Attaullah Mohmand",
    "Mohammad Malik Khuram",
    "Nafisa Tahiri",
    "Abdul Matin Rahmani",
    "Sabira Mohammadi",
    "Atiqullah Barialy",
    "Ahmad Omid Samit",
    "Zabihullah Sakha",
    "Ahmad Shah Subhani",
]

INTERVIEWER_NAME_MAP = {
    "عتیق الله بریالی": "Atiqullah Barialy",
    "احمد جاوید کریمی": "Ahmad Javid Karimi",
    "محمد اکبر": "Mohammad Akbar",
    "عطاءالله مهند": "Attaullah Mohmand",
    "عطاءالله": "Attaullah Mohmand",
    "عطاءالله مهمند": "Attaullah Mohmand",
    "محمد مالک خرم": "Mohammad Malik Khuram",
    "نفیسه طاهری": "Nafisa Tahiri",
    "عبدالمتین رحمانی": "Abdul Matin Rahmani",
    "صابره محمدی": "Sabira Mohammadi",
    "احمد امید": "Ahmad Omid Samit",
    "نفیسه": "Nafisa Tahiri",
    "محمد مالک": "Mohammad Malik Khuram",
    "احمد جاوید کریم": "Ahmad Javid Karimi",
    "ذبیح الله سخا": "Zabihullah Sakha",
    "صديق الله افکار": "Sadiqullah Afkar",
    "سميع الله ساحر": "Samiullah sahir",
    "قسيم کاموال.": "Qaseem kamawal",
    "قسيم کاموال": "Qaseem kamawal",
    "احمدشاه سبحانی": "Ahmad Shah Subhani",
    "احمدشاه": "Ahmad Shah Subhani",
    "قیام الدین امیری": "Qayamudin Amiri",
    "قیام الدین امیري": "Qayamudin Amiri",
    "فهيم راسا": "Fahimullah Rasa",
    "فهیم راسا": "Fahimullah Rasa",
    "فهیم": "Fahimullah Rasa",
    "فهيم": "Fahimullah Rasa",
    "حینا": "Hina Rasa",
    "حينا": "Hina Rasa",
    "ريحان الله مشواڼي": "Rihanullah Mashwani",
    "قسیم کاموال": "Qaseem kamawal",
    "ريحان الله مشواڼی": "Rihanullah Mashwani",
    "ریحان الله مشوانې": "Rihanullah Mashwani",
    "احمد شاه سبحانی": "Ahmad Shah Subhani",
    "محمدشاه سبحانی": "Ahmad Shah Subhani",
    "قسیم کاوال": "Qaseem kamawal",
    "صديق الله څ": "Sadiqullah Afkar",
    "قيام الدين اميری": "Qayamudin Amiri",
    "قسيم کامواا": "Qaseem kamawal",
    "فهيم الله رسا": "Fahimullah Rasa",
    "زرمينه سادات": "Zarmina Sadat",
    "حنا": "Hina Rasa",
    "ریحان الله مشواڼي": "Rihanullah Mashwani",
    "سمیع الله ساحر": "Samiullah sahir",
    "حناء": "Hina Rasa",
    "نصرالله مهمند": "Nasrullah Mohmand",
    "عتیق الله": "Atiqullah Barialy",
}

ENUMERATOR_TARGETS = [
    {"province": "Nangarhar", "district": "Acheen", "target_male": 12, "target_female": 4, "enumerator_name": "Fahimullah Rasa"},
    {"province": "Nangarhar", "district": "Behsud", "target_male": 3, "target_female": 3, "enumerator_name": "Sadiqullah Afkar"},
    {"province": "Nangarhar", "district": "Dara-i-Noor", "target_male": 151, "target_female": 13, "enumerator_name": "Rihanullah Mashwani"},
    {"province": "Nangarhar", "district": "Kot", "target_male": 5, "target_female": 3, "enumerator_name": "Qayamudin Amiri"},
    {"province": "Nangarhar", "district": "Kuz Kunar", "target_male": 15, "target_female": 5, "enumerator_name": "Hina Rasa"},
    {"province": "Nangarhar", "district": "Lalpur", "target_male": 12, "target_female": 2, "enumerator_name": "Samiullah sahir"},
    {"province": "Nangarhar", "district": "Shinwar", "target_male": 22, "target_female": 3, "enumerator_name": "Qaseem kamawal"},
    {"province": "Nangarhar", "district": "Spinghar", "target_male": 4, "target_female": 5, "enumerator_name": "Zarmina Sadat"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Ahmad Javid Karimi"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Nasrullah Mohmand"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Mohammad Akbar"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Attaullah Mohmand"},
    {"province": "Samangan", "district": "Aybak", "target_male": 129, "target_female": 23, "enumerator_name": "Mohammad Malik Khuram"},
    {"province": "Samangan", "district": "Feroz Nakhchir", "target_male": 118, "target_female": 9, "enumerator_name": "Nafisa Tahiri"},
    {"province": "Samangan", "district": "Hazrat-e- Sultan", "target_male": 140, "target_female": 9, "enumerator_name": "Abdul Matin Rahmani"},
    {"province": "Samangan", "district": "Khulm", "target_male": 149, "target_female": 8, "enumerator_name": "Sabira Mohammadi"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Atiqullah Barialy"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Ahmad Omid Samit"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Zabihullah Sakha"},
    {"province": "Samangan", "district": "", "target_male": 0, "target_female": 0, "enumerator_name": "Ahmad Shah Subhani"},
    {"province": "Laghman", "district": "Alingar", "target_male": 0, "target_female": 0, "enumerator_name": "Fahimullah Rasa"},
    {"province": "Laghman", "district": "Mihtarlam", "target_male": 0, "target_female": 0, "enumerator_name": "Hina Rasa"},
]
